spring:
  application:
    name: docker-test

  datasource:
    url: jdbc:mysql://localhost:3306/docker_test_db
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

