spring:
  application:
    name: docker-test

  datasource:
    url: jdbc:mysql://mysql:3306/docker_test_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update



